### ISSUE TITLE
Display unit cost in historical orders

### ISSUE THREAD

**Issue by davide-ceretti** [hashtock/hashtock-go#21]
Let's say I bought 12 shares of Apple for 120 and I sold them for 150.
It would be nice to show in the historical orders table how much one single Apple share was worth when I bought or sold it.

**Comment by mrfuxi** [comment]
I had that on my todo list for a while now :)

**Comment by mrfuxi** [comment]
Hmm, actually I had something similar. So I will do both.
You'll see... :)

**Comment by mrfuxi** [comment]
Note: Deployed
